/* ===== EBTOOLS — PRODUCT DATABASE ===== */
const WA = '5491171349389';

const PRODUCTS = [
  // CONSTRUCCIÓN
  { id:1,  name:'Abrochadoras Manuales',          slug:'abrochadoras-manuales',          cat:'construccion', img:'https://ebtools.com.ar/wp-content/uploads/2017/07/116-1024x1024.jpg',           short:'Para madera, cartón y chapas livianas.', desc:'Abrochadoras de acero tratado para uso intensivo en obras, carpintería y packaging. Diseñadas para trabajar con grapadoras J y T, garantizan un disparo limpio y preciso en cada aplicación. Ideales para quienes trabajan en volumen y necesitan velocidad sin sacrificar resultado.' },
  { id:2,  name:'Gaviones',                        slug:'gaviones',                        cat:'construccion', img:'https://ebtools.com.ar/wp-content/uploads/2017/12/Gavion1-1024x1024.jpg',         short:'Contención de suelos y paisajismo.',     desc:'Estructuras metálicas de malla hexagonal galvanizada para contención de taludes, canales y muros de contención. Su diseño modular permite adaptarse a diferentes geometrías de terreno. Alta resistencia a la corrosión y cargas de suelo.' },
  { id:3,  name:'Revocadoras Neumáticas',          slug:'revocadoras-neumaticas',          cat:'construccion', img:'https://ebtools.com.ar/wp-content/uploads/2021/01/50-1024x1024.jpg',             short:'Proyección de mortero de alto rendimiento.', desc:'Máquinas revocadoras neumáticas para proyección de mortero, cemento y yeso en superficies interiores y exteriores. Reducen drásticamente el tiempo de aplicación frente al revoque manual. Compatibles con compresores de 2HP o más.' },
  { id:4,  name:'Abrochadoras Neumáticas',         slug:'abrochadoras-neumaticas',         cat:'construccion', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/93.-1024x1024.jpg',            short:'Alta velocidad para obra continua.',     desc:'Abrochadoras neumáticas de cuerpo ligero y disparo secuencial o simple. Perfectas para armado de pallets, marcos de madera y estructuras livianas en obra. Alimentadas por aire comprimido, eliminan la fatiga del operario en jornadas intensivas.' },

  // GASTRONOMÍA
  { id:5,  name:'Clipeadoras Manual y Neumática',  slug:'clipeadoras-manual-neumatica',    cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2022/03/WhatsApp-Image-2022-03-22-at-14.05.06-3-1024x1024.jpeg', short:'Cierre profesional de embutidos.',       desc:'Clipeadoras para sellado de tripas en producción de embutidos. El modelo manual es ideal para producciones artesanales, mientras que el neumático multiplica la velocidad en líneas industriales. Utilizan clips de aluminio estándar de alta retención.' },
  { id:6,  name:'Pinza Abrochadora para Tripa',    slug:'pinza-abrochadora-tripa',         cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2017/07/116-1024x1024.jpg',           short:'Para salamines y chorizos.',            desc:'Pinza manual diseñada para el amarre y cierre de tripas de salamín, salchicha y chorizo. Construcción en acero inoxidable apto para uso alimentario. Ergonómica y de bajo mantenimiento para carnicerías y fábricas de embutidos.' },
  { id:7,  name:'Cortadora de Papas Bastón',       slug:'cortadora-papas-baston',          cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2025/12/WhatsApp_Image_2025-10-31_at_11.08.32-removebg-preview-4.png', short:'3 tipos de corte. Acero inox.', desc:'Cortadora gastronómica de palancas para papas fritas estilo bastón. Incluye 3 rejas de corte intercambiables (6mm, 8mm y 10mm). Cuerpo de acero inoxidable, fácil desmontaje para limpieza. Ideal para restaurantes y franquicias de comida rápida.' },
  { id:8,  name:'Embutidora Manual Horizontal 3L', slug:'embutidora-manual-horizontal-3l', cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2025/12/WhatsApp-Image-2025-12-03-at-11.59.47.jpeg', short:'Producción artesanal de embutidos.',     desc:'Embutidora horizontal de 3 litros con cilindro de acero inoxidable y sistema de palanca de dos velocidades. Permite un llenado uniforme y sin aire para salchichas, chorizos y morcillas. Incluye boquillas de 16, 22 y 32mm.' },
  { id:9,  name:'Multiprocesadora Industrial 5 Discos', slug:'multiprocesadora-industrial-5-discos', cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2025/12/WhatsApp-Image-2025-12-03-at-12.32.41-1024x725.jpeg', short:'Corte, rallado y laminado en segundos.', desc:'Procesadora de alimentos de uso profesional con 5 discos intercambiables: rallador, laminador, cortador en juliana, cortador fino y rebanador. Motor de alta potencia, recipiente de 5L. Para restaurantes, hoteles y cocinas industriales.' },
  { id:10, name:'Embutidoras Manual y Eléctrica',  slug:'embutidoras-manual-electrica',    cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2025/03/3-y-5L-1024x1024.jpg',          short:'3 y 5 litros. Inox alimentario.',       desc:'Línea completa de embutidoras en capacidades de 3 y 5 litros, disponibles en versión manual y eléctrica. Construcción en acero inoxidable 304 apto para industria alimentaria. La versión eléctrica incorpora motor de 180W con selector de velocidad.' },
  { id:11, name:'Atadora de Embutidos Manual',     slug:'atadora-embutidos-manual',        cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2022/08/Atadora-Chorizos-1024x1024.jpg', short:'Atado uniforme a alta velocidad.',       desc:'Máquina atadora manual para embutidos tipo salchicha y chorizo. Realiza el atado con hilo automáticamente, logrando porciones uniformes sin necesidad de anudar a mano. Compacta y de fácil ajuste para distintos diámetros de tripa.' },
  { id:12, name:'Cortadora de Fiambre Eléctrica',  slug:'cortadora-fiambre-electrica',     cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2025/12/WhatsApp-Image-2025-12-03-at-11.14.45-3.jpeg', short:'Disco 300mm. Espesor regulable.',        desc:'Cortadora eléctrica de fiambres y quesos con disco de acero inoxidable de 300mm. Corte regulable de 0 a 15mm de espesor. Bandeja de aluminio con guía antideslizante. Ideal para delis, supermercados y cocinas profesionales.' },
  { id:13, name:'Picadora de Carne Eléctrica N32', slug:'picadora-carne-electrica-n32',    cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2025/12/WhatsApp-Image-2025-11-03-at-13.30.07.jpeg', short:'Alta producción. Tornillo N°32.',         desc:'Picadora eléctrica de carne con cabezal N°32 y motor de alta potencia para producción continua. Incluye discos de 3mm, 6mm y 8mm. Cuerpo de aluminio fundido con acabado resistente a impactos. Producción estimada: 80-120kg/h.' },
  { id:14, name:'Clipeadora para Bolsas y Redes',  slug:'clipeadora-bolsas-redes',         cat:'gastronomia', img:'https://ebtools.com.ar/wp-content/uploads/2025/12/Sin-titulo-1-1024x1024.jpg',    short:'Sellado de bolsas y redes de malla.',   desc:'Clipeadora específicamente diseñada para el cierre de bolsas de polietileno y redes de malla usadas en packaging de carnes, frutas y verduras. Neumática o manual, aplica clip metálico estándar con un solo golpe. Producción: hasta 40 clips/min.' },

  // AGRO
  { id:15, name:'Tijeras de Poda',                 slug:'tijeras-poda',                    cat:'agro', img:'https://ebtools.com.ar/wp-content/uploads/2021/01/4a-1024x1024.jpg',               short:'Para viña, frutales y horticultura.',   desc:'Tijeras de poda con cuerpo de aluminio aeronáutico y hojas de acero SK5 endurecido. Diseño bypass de apertura regulable para adaptarse a distintos tamaños de mano. Disponibles en modelos manuales y neumáticos. Peso: 280g.' },
  { id:16, name:'Atadoras Tutoreadoras',           slug:'atadoras-tutoreadoras',            cat:'agro', img:'https://ebtools.com.ar/wp-content/uploads/2020/12/33-1024x1024.jpg',               short:'Para viñas, tomates y espárragos.',      desc:'Máquina atadora para sujeción de plantas a tutores y espalderas. Utiliza cinta de nylon y grapa metálica en un movimiento simultáneo. Multiplica por 10 la velocidad respecto al atado manual. Compatible con cintas de 0.06mm de grosor.' },
  { id:17, name:'Tijera y Navaja para Injertos',   slug:'tijera-navaja-injertos',           cat:'agro', img:'https://ebtools.com.ar/wp-content/uploads/2021/07/injertos-1024x1024.jpg',         short:'Cortes de injerto en omega y lengüeta.',desc:'Kit de herramientas para injertos de precisión que incluye tijera con cuchillas intercambiables para cortes en omega, lengüeta y recto, más navaja de injerto con hoja de carbono. Para viticultores y viveristas profesionales.' },
  { id:18, name:'Serruchos de Poda',               slug:'serruchos-poda',                  cat:'agro', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/serrucho-1-1024x1024.jpg',        short:'Corte limpio en ramas de hasta 80mm.',  desc:'Serruchos de poda con hoja curva de 30cm en acero de alto carbono con triple filo. El diseño curvo maximiza el corte en el movimiento de tracción. Mango ergonómico con grip antideslizante. Para ramas de hasta 80mm de diámetro.' },
  { id:19, name:'Pértigas Extensibles',            slug:'pertigas-extensibles',             cat:'agro', img:'https://ebtools.com.ar/wp-content/uploads/2022/03/palo3-1024x1024.jpg',            short:'Aluminio. Hasta 4 metros de largo.',    desc:'Pértigas telescópicas de aluminio de alta resistencia para acople de herramientas de altura. Extensibles desde 1.5m hasta 4m. Sistema de bloqueo por tuerca que mantiene la longitud con total seguridad durante el trabajo.' },
  { id:20, name:'Tijera Poda Extensible en Altura',slug:'tijera-poda-extensible-altura',   cat:'agro', img:'https://ebtools.com.ar/wp-content/uploads/2022/08/WhatsApp-Image-2022-06-01-at-10.08.33-AM-1.jpeg', short:'Poda y cosecha desde el suelo.', desc:'Tijera de poda telescópica que combina la funcionalidad de una tijera profesional con un palo extensible. Permite podar y cosechar en alturas de hasta 3.5m sin escalera. Accionamiento por cable de acero con gatillo ergonómico.' },

  // NEUMÁTICAS
  { id:21, name:'Llave de Impacto Neumática',      slug:'llave-impacto-neumatica',          cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/2-1-1024x1024.jpg',          short:'Torque: 680 Nm. Cuadro 1/2".',          desc:'Pistola de impacto neumática de cuadro 1/2" con torque máximo de 680 Nm. Mecanismo de doble martillo para mayor durabilidad. Consumo de aire: 140 l/min a 6.3 bar. Ideal para mecánica automotriz, talleres y mantenimiento industrial.' },
  { id:22, name:'Grasera Engrasadora Neumática',   slug:'grasera-engrasadora-neumatica',    cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/grasera7-1024x1024.jpg',      short:'Neumática y manual. 400cm³.',           desc:'Engrasadora de doble uso: neumática (accionada por compresor) y manual (palanca). Capacidad de cartucho 400cm³. Presión máxima: 700 bar. Manguera de 1.2m con boquilla giratoria. Para engrase de rodamientos, articulaciones y maquinaria agrícola.' },
  { id:23, name:'Kit Aire Comprimido Completo',    slug:'kit-aire-comprimido',               cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2021/01/kit-completo-1-1024x1024.jpg', short:'Pistola, manguera y acoples.',          desc:'Kit completo para conexión de herramientas neumáticas que incluye pistola sopladora, pico inflador, manómetro digital, acople rápido macho/hembra y manguera de 5m. Todo lo necesario para poner en marcha un compresor.' },
  { id:24, name:'Martillo Demoledor Neumático',    slug:'martillo-demoledor-neumatico',     cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2021/03/martillon-1024x1024.jpg',      short:'2500 golpes/min. Para hormigón.',        desc:'Martillo demoledor neumático de alta percusión para demolición de hormigón, extracción de azulejos y ruptura de pavimento. 2500 golpes/minuto. Vástago hexagonal de 28mm. Incluye cincel plano, cincel punta y escarpe.' },
  { id:25, name:'Amoladora Recta Neumática',       slug:'amoladora-recta-neumatica',        cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/amoladora2-1024x1024.jpg',    short:'25.000 RPM. Para piezas interiores.',   desc:'Amoladora recta neumática de alta velocidad (25.000 RPM) para desbaste y pulido en orificios, moldes y piezas de geometría compleja. Collet de 6mm, consumo de 140 l/min. Cuerpo delgado para acceso en espacios reducidos.' },
  { id:26, name:'Remachadora Pop Neumática',       slug:'remachadora-pop-neumatica',         cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/Remachadora-1024x1024.jpg',    short:'Hasta 800 remaches/hora.',              desc:'Remachadora neumática para remaches pop de aluminio y acero en diámetros 3.2, 4, 4.8 y 6.4mm. Ciclo completo automático (remache y extracción de mandril). Producción de hasta 800 remaches/hora. Para estructuras, chapa y carpintería metálica.' },
  { id:27, name:'Pistolas para Sopletear',         slug:'pistolas-sopletear',               cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2021/01/kit2-1024x1024.jpg',          short:'Limpieza por soplado de alta potencia.', desc:'Pistolas de soplado neumático con cañón de acero y válvula de gatillo regulable. Para limpieza de virutas, polvo y humedad en maquinaria, circuitos electrónicos y superficies de trabajo. Presión regulable 0-8 bar.' },
  { id:28, name:'Amoladora Cortadora Neumática',   slug:'amoladora-cortadora-neumatica',    cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/amoladora2-2-1024x1024.jpg',  short:'Disco 115mm. 10.000 RPM.',              desc:'Amoladora angular neumática para disco de corte de 115mm (4.5"). Velocidad libre: 10.000 RPM. Consumo: 170 l/min. Cuerpo de aluminio con empuñadura lateral orientable. Para corte de metales, tuberías y estructuras.' },
  { id:29, name:'Llave Impacto Camión Profesional',slug:'llave-impacto-camion-profesional', cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2021/09/LLIC-3-1024x1024.jpg',         short:'1" cuadro. 2700 Nm máximo.',            desc:'Llave de impacto de cuadro 1" para servicio pesado en camiones, maquinaria agrícola y equipos de construcción. Torque máximo: 2700 Nm. Triple martillo para mayor eficiencia. Consumo de aire: 600 l/min a 6.2 bar.' },
  { id:30, name:'Lijadora Orbital Neumática 150mm',slug:'lijadora-orbital-neumatica-150mm', cat:'neumaticas', img:'https://ebtools.com.ar/wp-content/uploads/2022/08/Lijadora2-1024x1024.jpg',      short:'Base 150mm. 12.000 OPM.',               desc:'Lijadora roto-orbital neumática con base de 150mm (6") y velocidad de 12.000 OPM. Sistema de fijación de lija por velcro. Extracción de polvo por orificio central. Para acabados en carrocería, madera y fibra de vidrio.' },

  // SOPLETES
  { id:31, name:'Pistola Soplete para Arenar',     slug:'pistola-soplete-arenar',           cat:'sopletes', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/PistolaArena-copy-1024x1024.jpg', short:'Arenado por succión y presión.',         desc:'Pistola de arenado neumático por succión para limpieza de óxido, pintura y contaminantes superficiales. Boquilla de carburo de boro de larga duración. Compatible con arena silícea, granalla y microesferas. Para preparación de superficies metálicas.' },
  { id:32, name:'Pistola Pintura por Succión',     slug:'pistola-pintura-succion',           cat:'sopletes', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/PistolaAire1-1-1024x1024.jpg',  short:'Vaso inferior 600ml. HVLP.',            desc:'Pistola soplete de pintura por succión con vaso de aluminio de 600ml. Sistema HVLP (alto volumen, baja presión) para mejor transfer y menor desperdicio de material. Boquilla regulable de 1.5 y 1.8mm. Para lacas, esmaltes y fondos.' },
  { id:33, name:'Pistola Soplete por Gravedad',    slug:'pistola-soplete-gravedad',          cat:'sopletes', img:'https://ebtools.com.ar/wp-content/uploads/2021/07/pistolavaso1-1024x1024.jpg',     short:'Vaso superior 600ml. Alta atomización.',desc:'Pistola de pintura por gravedad con vaso superior de aluminio de 600ml. Alta atomización para acabados de primera calidad en carrocería y carpintería. Aguja de acero inoxidable, cabezal de aluminio mecanizado. Boquilla 1.4mm incluida.' },
  { id:34, name:'Pistola Pintura Tolva 5L',        slug:'pistola-pintura-tolva-5l',          cat:'sopletes', img:'https://ebtools.com.ar/wp-content/uploads/2021/03/Pistola-Pintar-Aluminio1-1-1024x1024.jpg', short:'Para grandes superficies. 5 litros.',  desc:'Pistola tolva de gran capacidad (5 litros) para aplicación de pintura en paredes, cielos rasos y grandes superficies industriales. Reduce la cantidad de recargas y aumenta la productividad. Compatible con pintura látex, epoxi y caucho clorado.' },

  // FILTROS Y ACOPLES
  { id:35, name:'Unidad Filtro Compresor',         slug:'unidad-filtro-compresor',           cat:'filtros', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/FilrtoAire1-1024x1024.jpg',     short:'Filtrado y regulación en un cuerpo.',   desc:'Unidad de mantenimiento de aire comprimido que integra filtro de partículas, regulador de presión y manómetro en un solo cuerpo. Conexión 1/4" NPT. Vaso de policarbonato desmontable para limpieza. Para todo tipo de herramientas neumáticas.' },
  { id:36, name:'Manómetro Medidor de Presión',    slug:'manometro-medidor-presion',         cat:'filtros', img:'https://ebtools.com.ar/wp-content/uploads/2022/03/M2-1024x1024.jpg',              short:'0 a 16 bar. Esfera 63mm.',              desc:'Manómetro de bourdon para medir presión de aire en sistemas neumáticos. Escala dual bar/PSI de 0-16 bar. Cuerpo de acero con esfera de glicerina para amortiguación de golpes. Conexión inferior 1/4" BSP. Para montaje en línea o panel.' },
  { id:37, name:'Filtro Trampa de Agua',           slug:'filtro-trampa-agua',               cat:'filtros', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/filtro-1024x1024.jpg',          short:'Retiene humedad y partículas.',         desc:'Filtro separador de agua y aceite para líneas de aire comprimido. Vaso de policarbonato transparente con drenaje automático. Conexión 1/4" NPT. Esencial para proteger herramientas neumáticas y asegurar calidad en aplicaciones de pintura.' },
  { id:38, name:'Mini Lubricador',                 slug:'mini-lubricador',                  cat:'filtros', img:'https://ebtools.com.ar/wp-content/uploads/2021/07/WhatsApp-Image-2021-04-28-at-11.10.09-AM.jpeg', short:'Dosificación de aceite en línea.',       desc:'Lubricador de línea neumática que incorpora aceite en neblina al flujo de aire, lubricando automáticamente todas las herramientas conectadas. Depósito de 30ml, ajuste de dosificación por tornillo exterior. Conexión 1/4" NPT.' },
  { id:39, name:'Acoples Rápidos',                 slug:'acoples-rapidos',                  cat:'filtros', img:'https://ebtools.com.ar/wp-content/uploads/2021/07/acoples-1024x1024.jpg',        short:'Conexión y desconexión en un movimiento.', desc:'Acoples rápidos de acero pavonado para conexión/desconexión sin herramientas de mangueras y herramientas neumáticas. Disponibles en tapones y enchufes tipo ARO (industrial). Presión máxima: 16 bar. Pares macho/hembra.' },
  { id:40, name:'Pico para Inflar',                slug:'pico-para-inflar',                 cat:'filtros', img:'https://ebtools.com.ar/wp-content/uploads/2022/08/Pico-inflador-1024x1024.jpg',  short:'Válvula Schrader y aguja de pelota.',   desc:'Pico inflador para válvulas Schrader (neumáticos) y aguja para pelotas. Cuerpo de latón con cierre de goma. Conexión a manguera o pistola de aire. Para gomería, bicicleterías y uso general.' },

  // REPUESTOS COMPRESORES
  { id:41, name:'Presostato 380V',                 slug:'presostato-380v',                  cat:'repuestos', img:'https://ebtools.com.ar/wp-content/uploads/2021/09/Preso-4-380-1024x1024.jpg',  short:'Trifásico. 4 salidas. Hasta 12 bar.',   desc:'Presostato trifásico 380V para control automático de compresores industriales. 4 salidas de aire + purga automática. Rango de presión regulable 6-12 bar. Terminales de 40A. Apto para compresores de 5HP a 15HP en instalaciones trifásicas.' },
  { id:42, name:'Regulador Caudal Aire 1/4"',      slug:'regulador-caudal-aire',             cat:'repuestos', img:'https://ebtools.com.ar/wp-content/uploads/2022/03/RR1-1024x1024.jpg',           short:'Ajuste preciso de presión de salida.',  desc:'Regulador de presión de aire con manómetro incorporado para ajuste fino de la presión de trabajo. Conexión 1/4" NPT entrada/salida. Rango 0.5-10 bar. Cuerpo de aluminio con perilla de bloqueo. Para herramientas neumáticas de precisión.' },
  { id:43, name:'Válvulas Anti Retorno',           slug:'valvulas-anti-retorno',             cat:'repuestos', img:'https://ebtools.com.ar/wp-content/uploads/2022/08/WhatsApp-Image-2022-05-16-at-16.25.46-1-1024x1024.jpeg', short:'Previene el retorno de flujo.',         desc:'Válvulas de retención (check valves) para instalaciones de aire comprimido. Evitan el retorno de aire hacia el compresor al detener la máquina. Cuerpo de latón, disponibles en 1/4", 3/8" y 1/2" BSP. Presión máxima: 16 bar.' },
  { id:44, name:'Regulador de Aire Compresor',     slug:'regulador-aire-compresor',          cat:'repuestos', img:'https://ebtools.com.ar/wp-content/uploads/2022/08/R-1024x1024.jpg',             short:'Sin manómetro. Para panel o línea.',    desc:'Regulador de presión de cuerpo compacto para instalación en panel o directamente en la salida del compresor. Sin manómetro (para usar con manómetro externo). Conexión 1/4" NPT. Regulación continua 0-10 bar.' },
  { id:45, name:'Manómetro',                       slug:'manometro',                        cat:'repuestos', img:'https://ebtools.com.ar/wp-content/uploads/2024/01/Manometro-solo-1024x1024.jpg', short:'Conexión trasera. 10 bar.',             desc:'Manómetro de repuesto para compresores y unidades de mantenimiento. Escala 0-10 bar, conexión trasera 1/8" BSP. Esfera de 40mm con indicador rojo de presión máxima. Compatible con la mayoría de compresores del mercado.' },
  { id:46, name:'Presostato 220V',                 slug:'presostato-220v',                  cat:'repuestos', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/Persostato4-2-1024x1024.jpg', short:'Monofásico. Purga automática.',         desc:'Presostato monofásico 220V para compresores domésticos e industriales de hasta 10HP. 4 salidas de 1/4" + purga automática de condensado. Rango ajustable 6-10 bar. Terminales de 20A protegidos. Reemplaza presostatos de la mayoría de marcas.' },
  { id:47, name:'Base Presostato con Regulador',   slug:'base-presostato-regulador',         cat:'repuestos', img:'https://ebtools.com.ar/wp-content/uploads/2022/03/BP2-1024x1024.jpg',          short:'Presostato + regulador integrado.',     desc:'Base multipunto que integra presostato, regulador de presión con manómetro y múltiples salidas de 1/4". Simplifica la instalación al concentrar en un solo componente el control y distribución del aire comprimido. Para compresores 220V.' },
  { id:48, name:'Válvula de Seguridad Calibrada',  slug:'valvula-seguridad-calibrada',       cat:'repuestos', img:'https://ebtools.com.ar/wp-content/uploads/2022/08/V5-1024x1024.jpg',            short:'Calibrada en fábrica a 8, 10 o 12 bar.',desc:'Válvulas de seguridad (alivio) calibradas de fábrica para distintas presiones: 8, 10 y 12 bar. Conexión 1/4" BSP. Cuerpo de latón cromado. Obligatoria en toda instalación de compresor según normativa de recipientes a presión.' },
  { id:49, name:'Válvula de Salida Aire',          slug:'valvula-salida-aire',               cat:'repuestos', img:'https://ebtools.com.ar/wp-content/uploads/2022/08/V2-1024x1024.jpg',            short:'Llave de paso 1/4" para compresor.',    desc:'Válvula de esfera de paso total para salida de aire de compresores. Cuerpo de latón con palanca de accionamiento rápido. Conexión 1/4" BSP. Para instalación directa en la salida del tanque o en manifold de distribución.' },

  // MANGUERAS
  { id:50, name:'Mangueras Espiraladas',           slug:'mangueras-espiraladas',             cat:'mangueras', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/manguera3-1024x1024.jpg',    short:'Retráctil. 10m extendida. 1/4".',       desc:'Mangueras espiraladas (retráctiles) de poliuretano para herramientas neumáticas. Se extienden hasta 10m y vuelven a su longitud original (2m). Acoples de 1/4" macho en ambos extremos. Evitan enredos y tropiezos en el área de trabajo.' },
  { id:51, name:'Manguera PVC Alta Presión',       slug:'manguera-pvc-alta-presion',         cat:'mangueras', img:'https://ebtools.com.ar/wp-content/uploads/2021/02/56-1024x1024.jpg',           short:'Hasta 20 bar. Reforzada 3 trenzas.',    desc:'Manguera de PVC plastificado con triple refuerzo de trenzado de poliéster. Presión de trabajo: 20 bar. Presión de rotura: 60 bar. Diámetro interior 6mm (1/4"). Disponible en bobinas de 25 y 50 metros o cortada a medida.' },
  { id:52, name:'Pico Inflador con Manómetro',     slug:'pico-inflador-manometro',           cat:'mangueras', img:'https://ebtools.com.ar/wp-content/uploads/2021/01/kit4-1024x1024.jpg',          short:'Inflado controlado con lectura directa.',desc:'Pico inflador con manómetro incorporado para inflado preciso de neumáticos de autos, motos y camiones. Escala dual bar/PSI. Permite inflar y desinflar con control visual permanente de la presión. Válvula Schrader universal.' },
  { id:53, name:'Manómetro para Neumáticos',       slug:'manometro-neumaticos',              cat:'mangueras', img:'https://ebtools.com.ar/wp-content/uploads/2022/03/M-1024x1024.jpg',             short:'Lápiz de presión digital. 0-60 PSI.',   desc:'Medidor de presión de neumáticos en formato lápiz. Escala 0-60 PSI / 0-4 bar. Lectura digital inmediata. Cuerpo de aluminio anodizado con funda de goma protectora. Imprescindible en gomería, automotores y vehículos de trabajo.' },
];

const CATEGORIES = [
  { key:'construccion', label:'Construcción',      icon:`<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M3 21h18M5 21V7l7-4 7 4v14M9 21v-6h6v6"/></svg>` },
  { key:'gastronomia',  label:'Gastronomía',        icon:`<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M18 8h1a4 4 0 0 1 0 8h-1M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8zM6 1v3M10 1v3M14 1v3"/></svg>` },
  { key:'agro',         label:'Agro',               icon:`<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M12 2a10 10 0 0 1 0 20M12 2a10 10 0 0 0 0 20M12 2v20M2 12h20"/></svg>` },
  { key:'neumaticas',   label:'Neumaticas',         icon:`<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>` },
  { key:'sopletes',     label:'Sopletes',           icon:`<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M5 8h14M5 8a2 2 0 1 0 0-4h14a2 2 0 1 0 0 4M5 8v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/></svg>` },
  { key:'filtros',      label:'Filtros y Acoples',  icon:`<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M22 3H2l8 9.46V19l4 2v-8.54L22 3z"/></svg>` },
  { key:'repuestos',    label:'Repuestos',           icon:`<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.07 4.93A10 10 0 1 0 4.93 19.07"/><path d="M19.07 4.93l-3 3M4.93 19.07l3-3"/></svg>` },
  { key:'mangueras',    label:'Mangueras',           icon:`<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M4 4h4l2 2h4l2-2h4M4 4v4a8 8 0 0 0 16 0V4"/></svg>` },
];

function getCatLabel(key) {
  return CATEGORIES.find(c => c.key === key)?.label || key;
}

function waMsg(productName) {
  const msg = `Hola EBTOOLS! Me interesa el producto: *${productName}*. ¿Me podrían dar información y precio? Gracias!`;
  return `https://wa.me/${WA}?text=${encodeURIComponent(msg)}`;
}

function getProductById(id) {
  return PRODUCTS.find(p => p.id === parseInt(id));
}

function getRelated(product, limit = 4) {
  return PRODUCTS.filter(p => p.cat === product.cat && p.id !== product.id).slice(0, limit);
}
