-- =====================================================================
--  EBTOOLS — ESQUEMA DE ANALYTICS
--  Ejecutar UNA vez en: Supabase -> SQL Editor -> New query -> Run
--  Crea la tabla de eventos, índices y políticas RLS.
--
--  Modelo de seguridad (igual que el resto del sitio):
--    - Cualquier visitante (anon) puede INSERTAR eventos (para poder trackear).
--    - Solo el admin logueado (authenticated) puede LEER los eventos.
--    - Nadie puede editar ni borrar desde el cliente.
--  No se guarda ningún dato personal: solo IDs anónimos generados en el navegador.
-- =====================================================================

-- ---------- TABLA ----------
create table if not exists analytics_events (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  session_id  text,               -- id anónimo de la visita (por pestaña)
  visitor_id  text,               -- id anónimo persistente (nuevo vs recurrente)
  type        text not null,      -- pageview, product_view, search, whatsapp_click, ...
  path        text,               -- inicio, producto, ...
  product_id  bigint,             -- si el evento es sobre un producto
  query       text,               -- texto del buscador (solo en type='search')
  meta        jsonb not null default '{}'::jsonb
);

-- ---------- ÍNDICES (para que el panel cargue rápido) ----------
create index if not exists ae_created_idx  on analytics_events (created_at desc);
create index if not exists ae_type_idx     on analytics_events (type);
create index if not exists ae_session_idx  on analytics_events (session_id);
create index if not exists ae_product_idx  on analytics_events (product_id) where product_id is not null;
create index if not exists ae_query_idx    on analytics_events (query)      where query is not null;

-- ---------- RLS ----------
alter table analytics_events enable row level security;

-- INSERT público (visitantes anónimos + logueados). Solo pueden insertar.
drop policy if exists "analytics public insert" on analytics_events;
create policy "analytics public insert"
  on analytics_events for insert
  to anon, authenticated
  with check (true);

-- SELECT solo para el admin logueado (backoffice).
drop policy if exists "analytics admin read" on analytics_events;
create policy "analytics admin read"
  on analytics_events for select
  to authenticated
  using (true);

-- (No se crean políticas de UPDATE/DELETE: quedan prohibidas desde el cliente.)

-- =====================================================================
--  OPCIONAL — Limpieza automática de eventos viejos (retención 12 meses).
--  Descomentá si querés que la tabla no crezca indefinidamente. Requiere la
--  extensión pg_cron (Supabase -> Database -> Extensions -> pg_cron).
-- =====================================================================
-- create extension if not exists pg_cron;
-- select cron.schedule('eb-analytics-cleanup', '0 4 * * *', $$
--   delete from analytics_events where created_at < now() - interval '12 months';
-- $$);
